apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: bundle-snapshot-bundle-resolver-example
  labels:
    app.kubernetes.io/name: bundle-tool
    app.kubernetes.io/component: taskrun
spec:
  taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/task-bundle-snapshot-from-bundle:latest
    - name: name
      value: bundle-snapshot-from-bundle
    - name: kind
      value: task
  params:
  - name: BUNDLE_IMAGE
    value: "quay.io/operator-framework/example-operator-bundle:v1.0.0"
  - name: IDMS_PATH
    value: ".tekton/images-mirror-set.yaml"
  - name: ICSP_PATH
    value: ""  # Not using legacy ICSP
  - name: VERIFY_PROVENANCE
    value: "true"
  - name: OUTPUT_FILE
    value: "generated-snapshot.yaml"
  - name: APPLICATION_NAME
    value: ""  # Will be extracted from bundle image
  - name: NAMESPACE
    value: "my-namespace"
  - name: BUNDLE_TOOL_IMAGE
    value: "konflux-ci/bundle-tool:latest"
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: source-workspace-pvc
---
# Example PVC for the workspace
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi