apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: generate-related-images-no-mirror-example
  labels:
    app.kubernetes.io/name: bundle-tool
    app.kubernetes.io/component: script-runner
  annotations:
    description: "Example of using bundle-tool generate-related-images without mirror policy"
spec:
  taskRef:
    resolver: bundles
    params:
    - name: bundle
      value: quay.io/konflux-ci/tekton-catalog/task-run-script-oci-ta:latest
    - name: name
      value: run-script-oci-ta
    - name: kind
      value: task
  params:
  - name: SOURCE_ARTIFACT
    value: "oci://quay.io/my-org/source-artifacts:latest"
  - name: ociStorage
    value: "quay.io/my-org/artifacts"
  - name: ociArtifactExpiresAfter
    value: ""
  - name: SCRIPT
    value: "bundle-tool generate-related-images bundle/"
  - name: SCRIPT_RUNNER_IMAGE
    value: "quay.io/konflux-ci/operator-sdk-builder:latest"
  - name: HERMETIC
    value: "false"