apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/operator-sdk-builder?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: operator-sdk-builder
    appstudio.openshift.io/component: operator-sdk-builder
    pipelines.appstudio.openshift.io/type: build
  name: operator-sdk-builder-on-push
  namespace: konflux-build-pipeli-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/konflux-build-pipeli-tenant/operator-sdk-builder/operator-sdk-builder:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
        - linux/ppc64le
        - linux/s390x
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: .
    - name: prefetch-input
      value: '[{"path":"kustomize/kustomize","type":"gomod"},{"path":"operator-registry","type":"gomod"},{"path":"operator-sdk","type":"gomod"},{"path":".","type":"rpm"}]'
    - name: hermetic
      value: "true"
    - name: build-source-image
      value: "true"
  taskRunSpecs:
    - pipelineTaskName: build-source-image
      stepSpecs:
        - computeResources:
            limits:
              memory: 3Gi
            requests:
              memory: 3Gi
          name: build
  taskRunTemplate:
    serviceAccountName: build-pipeline-operator-sdk-builder
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build-pipeline
status: {}
